### ISSUE TITLE
Improving the readme

### ISSUE THREAD

**Issue by guillaumebriday** [kernelkaribou/synology-monitoring#1]
Hey 👋 thanks for the job

I got few questions, how did you install InfluxDB ? With Docker ? 
Could you add some details in the readme for the global setup of influxdb, grafana and your script ?

Thank you in advance

**Comment by kernelkaribou** [comment]
Hello!

I did not intend to have this dive into the world of installing influx and grafana as it is was more for capturing. There are many documents online about setting up a docker for these services.  Assuming you have docker installed, I use these docker container creations for my grafana and influxdb instances.

**For Influxdb**

docker create \
--name=influxdb \
--restart=unless-stopped \
-e INFLUXDB_HTTP_AUTH_ENABLED=true \
-e INFLUXDB_DB="DBNAME" \
-e INFLUXDB_ADMIN_USER="ADMINUSER" \
-e INFLUXDB_ADMIN_PASSWORD="PASSWORDHERE" \
-e INFLUXDB_USER="NORMALUSER" \
-e INFLUXDB_USER_PASSWORD="PASSWORDHERE" \
-v /path/to/influx_folder:/var/lib/influxdb \
-p 8086:8086 \
influxdb:latest

**For Grafana**

docker create \
--name=grafana \
--hostname=GRAFANA \
--restart=unless-stopped \
-e TZ=America/Chicago \
-v /path/to/grafana_folder:/var/lib/grafana \
-p 3000:3000 \
grafana/grafana:latest

As I won't be committing to updating the readme for these, I will close this but hope the above commands help.
