### ISSUE TITLE
Database name Default was not found

### ISSUE THREAD

**Issue by blop135** [kernelkaribou/synology-monitoring#10]
Hi,

First thank you for this script. I have a problem.
Indeed it doesn't seems to to find the datas in the database but I don't know where the problem is from.
I'm sure about the path of my script in my task scheduler even if I have no results when I check the results via the task scheduler and I'm sure about the infos I putted in the script.sh.
What to I put in community? public?

Thank you in advance.

**Comment by Matt-L-KZ7MFL** [comment]
To fix this issue you have to make a few edits to the .json file. Open the file up and locate the words "datasource=Default" and replace with "datasource=default". This should fix the problem.

**Comment by blop135** [comment]
Indeed, it solved that problem, I replaced Holocron too by default because it didn't find it. 
Still I have no data so I went to my NAS through SSH and ran the script manually. And I have this messages:
![image](https://user-images.githubusercontent.com/36743019/78220816-8742c980-74c2-11ea-9658-139ab9f69b7e.png)

Do you know where it comes from? 

Thank you :)

**Comment by Matt-L-KZ7MFL** [comment]
Run the script using the task scheduler. In your files next to your .sh file there should be a new folder called synoscheduler. In there you can find the output.log file. What does it say is the problem on that file?

**Comment by blop135** [comment]
Well I've done it through the scheduler, but I don't have any folder synoscheduler. what is weird is that I don't have any result shown neither in the taskscheduler even if I'm absolutely sure about my path. I checked it 3 times to be sure I didn't make a mistake.

![image](https://user-images.githubusercontent.com/36743019/78533946-08170380-77ea-11ea-8c39-8f468d35e178.png)
![image](https://user-images.githubusercontent.com/36743019/78533993-19f8a680-77ea-11ea-98eb-a52d95edfb00.png)

![image](https://user-images.githubusercontent.com/36743019/78534094-2f6dd080-77ea-11ea-9599-3848783bbae4.png)

I don't why I don't have any results.

**Comment by blop135** [comment]
Ok I ended up figuring why. I juste commented the datas that he couldn't recover.

**Comment by blop135** [comment]
There's something I don't understand tough. When I go into my .json to modify the datasources to match the name of my database that content my synology snmp datas. It doesn't take it into consideration.
But when I put my Synology database into default  in Grafana, then my datas shows up. And when I go into my Synology dashboard and goes to Synology metrics -> explore -> it points to the default one even tough I changed them in the .json  file even before I imported it.

Any ideas?

Thanks :)

**Comment by kernelkaribou** [comment]
@blop135 are you making that change everywhere or just that single line.  That is going to be specific for a variable. There was some bugs in the template that were using a literal value of Default and also a reference to an old db. At this point it should be utilizing the true 'default' option in Grafana where your default data source is what is pulled from. If you have a different data source, I would suggest changing that in grafana from the dropdown rather than writing it in. If anything to avoid any simple typos or case sensitivity.

**Comment by kernelkaribou** [comment]
@Matt-L-KZ7MFL Thanks for the tips, went back and cleaned up the template to reflect this 'default' change for all values
