### ISSUE TITLE
 $'\r': command not found

### ISSUE THREAD

**Issue by vankhon** [kernelkaribou/synology-monitoring#12]
Hi, I enabled SNMP Services and set community to public.

After running the script, i get this error:
/volume1/homes/jan/grafana.sh: line 2: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 5: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 15: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 18: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 23: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 30: $'\r': command not found
/volume1/homes/jan/grafana.sh: line 69: syntax error near unexpected token `elif'
/volume1/homes/jan/grafana.sh: line 69: `            elif [[ $line == SYNOLOGY-SYSTEM-MIB::upgradeAvailable.0* ]]; then'

Theres no content in the InfluxDB

**Comment by kernelkaribou** [comment]
Given the error, I believe this may have to do with how the file was saved. Looks like the application used may have inserted control characters that are being interpreted by bash.  When you consider that lines such as #2 and #5 are empty lines of the script. If you look up the error there are many different suggestions on cleaning this up either in an editor or if anything do a git pull of the file or even a wget of the raw file itself.

`https://raw.githubusercontent.com/kernelkaribou/synology-monitoring/master/synology_snmp.sh`

**Comment by kernelkaribou** [comment]
Issue is on file formatting and not script, closing.
