### ISSUE TITLE
still references to Holocron

### ISSUE THREAD

**Issue by davemcmath** [kernelkaribou/synology-monitoring#3]
Line 1650 - Still says Holocron.

Also would it not be better to change all the "Defaults" to "InfluxDB" which is the name the influxDB connection gets as a default when connecting to Grafana.

Else call out in your readme that you need to rename your influxBD to "Default".

Thanks for the work by the way - not got it fully working yet, but they're the issues I've had so far.

**Comment by kernelkaribou** [comment]
Should be updated in latest grafana template update.
