### ISSUE TITLE
question on script error

### ISSUE THREAD

**Issue by stownplayer** [kernelkaribou/synology-monitoring#5]
I'm getting "timeout: no response from xxxxx" I get the same from localhost or if I input the ip address.  Any ideas why the script won't run or how to troubleshoot?

I'd love to test this out but i don't see why the script can't get a response from localhost....

**Comment by stownplayer** [comment]
got it.... nevermind. SNMP needed to be "public"

**Comment by stownplayer** [comment]
nevermind.... one step resolved another issue present. 

Task Scheduler has completed a scheduled task.

Task: Synology to Grafana
Start time: Sun, 11 Aug 2019 16:07:59 GMT
Stop time: Sun, 11 Aug 2019 16:08:47 GMT
Current status: 0 (Normal)
Standard output/error:
Capturing 3 times
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  2258  100   192  100  2066  10770   113k --:--:-- --:--:-- --:--:--  118k
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: b96b28ac-bc73-11e9-bd53-b827eba56b19
X-Influxdb-Build: OSS
X-Influxdb-Error: partial write: unable to parse 'synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100': invalid boolean dropped=0
X-Influxdb-Version: 1.7.7
X-Request-Id: b96b28ac-bc73-11e9-bd53-b827eba56b19
Date: Sun, 11 Aug 2019 20:08:02 GMT
Content-Length: 192

{"error":"partial write: unable to parse 'synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100': invalid boolean dropped=0"}
synology_system,nas_name=HomeNas01 uptime=290181365,system_status=1,fan_status=1,model="DS416",serial_number="1730NKN635900",upgrade_status=2,dsm_version="DSM 6.2-24922",system_temp=48
synology_memory,nas_name=HomeNas01 mem_total=1030856,mem_avail_real=16508,mem_buffer=26100,mem_cached=627120,mem_free=1865936
synology_cpu,nas_name=HomeNas01 usage_idle=56
synology_volume,nas_name=HomeNas01,volume=/volume1 vol_totalsize=5943940153344,vol_used=3529453043712
synology_raid,nas_name=HomeNas01,raid_name=Volume1 raid_status=1,raid_free_size=2414365474816,raid_total_size=5943940153344
synology_disk,nas_name=HomeNas01,disk_name=Drive1 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=32,disk_status=1
synology_disk,nas_name=HomeNas01,disk_name=Drive2 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=33,disk_status=1
synology_disk,nas_name=HomeNas01,disk_name=Drive3 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=32,disk_status=1
synology_disk,nas_name=HomeNas01,disk_name=Drive4 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=34,disk_status=1
synology_disk,nas_name=HomeNas01,disk_path=/dev/sda disk_reads=769211114496,disk_writes=519381221376,disk_load=5
synology_disk,nas_name=HomeNas01,disk_path=/dev/sdb disk_reads=714221472768,disk_writes=519381221376,disk_load=5
synology_disk,nas_name=HomeNas01,disk_path=/dev/sdc disk_reads=746404293632,disk_writes=518208094208,disk_load=5
synology_disk,nas_name=HomeNas01,disk_path=/dev/sdd disk_reads=711250851840,disk_writes=518208094208,disk_load=5
synology_disk,nas_name=HomeNas01,disk_path=/dev/sdq disk_reads=1833965675008,disk_writes=820172623872,disk_load=0
synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100
synology_network,nas_name=HomeNas01,interface_name=eth0 bytes_recv=2344501043,bytes_sent=1784048118
synology_network,nas_name=HomeNas01,interface_name=eth1 bytes_recv=3145349500,bytes_sent=4024720623
synology_network,nas_name=HomeNas01,interface_name=bond0 bytes_recv=5489850543,bytes_sent=5808768741

Capture #1 complete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  2258  100   192  100  2066  11572   121k --:--:-- --:--:-- --:--:--  126k
HTTP/1.1 100 Continue

**Comment by bboerzel** [comment]
> nevermind.... one step resolved another issue present.
> 
> Task Scheduler has completed a scheduled task.
> 
> Task: Synology to Grafana
> Start time: Sun, 11 Aug 2019 16:07:59 GMT
> Stop time: Sun, 11 Aug 2019 16:08:47 GMT
> Current status: 0 (Normal)
> Standard output/error:
> Capturing 3 times
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0100 2258 100 192 100 2066 10770 113k --:--:-- --:--:-- --:--:-- 118k
> HTTP/1.1 100 Continue
> 
> HTTP/1.1 400 Bad Request
> Content-Type: application/json
> Request-Id: b96b28ac-bc73-11e9-bd53-b827eba56b19
> X-Influxdb-Build: OSS
> X-Influxdb-Error: partial write: unable to parse 'synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100': invalid boolean dropped=0
> X-Influxdb-Version: 1.7.7
> X-Request-Id: b96b28ac-bc73-11e9-bd53-b827eba56b19
> Date: Sun, 11 Aug 2019 20:08:02 GMT
> Content-Length: 192
> 
> {"error":"partial write: unable to parse 'synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100': invalid boolean dropped=0"}
> synology_system,nas_name=HomeNas01 uptime=290181365,system_status=1,fan_status=1,model="DS416",serial_number="1730NKN635900",upgrade_status=2,dsm_version="DSM 6.2-24922",system_temp=48
> synology_memory,nas_name=HomeNas01 mem_total=1030856,mem_avail_real=16508,mem_buffer=26100,mem_cached=627120,mem_free=1865936
> synology_cpu,nas_name=HomeNas01 usage_idle=56
> synology_volume,nas_name=HomeNas01,volume=/volume1 vol_totalsize=5943940153344,vol_used=3529453043712
> synology_raid,nas_name=HomeNas01,raid_name=Volume1 raid_status=1,raid_free_size=2414365474816,raid_total_size=5943940153344
> synology_disk,nas_name=HomeNas01,disk_name=Drive1 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=32,disk_status=1
> synology_disk,nas_name=HomeNas01,disk_name=Drive2 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=33,disk_status=1
> synology_disk,nas_name=HomeNas01,disk_name=Drive3 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=32,disk_status=1
> synology_disk,nas_name=HomeNas01,disk_name=Drive4 disk_model="WD30EFRX-68EUZN0",disk_type="SATA",disk_temp=34,disk_status=1
> synology_disk,nas_name=HomeNas01,disk_path=/dev/sda disk_reads=769211114496,disk_writes=519381221376,disk_load=5
> synology_disk,nas_name=HomeNas01,disk_path=/dev/sdb disk_reads=714221472768,disk_writes=519381221376,disk_load=5
> synology_disk,nas_name=HomeNas01,disk_path=/dev/sdc disk_reads=746404293632,disk_writes=518208094208,disk_load=5
> synology_disk,nas_name=HomeNas01,disk_path=/dev/sdd disk_reads=711250851840,disk_writes=518208094208,disk_load=5
> synology_disk,nas_name=HomeNas01,disk_path=/dev/sdq disk_reads=1833965675008,disk_writes=820172623872,disk_load=0
> synology_ups,nas_name=HomeNas01,ups_group=NAS ups_status=OL LB,ups_load=11,ups_battery_runtime=0,ups_battery_charge=100
> synology_network,nas_name=HomeNas01,interface_name=eth0 bytes_recv=2344501043,bytes_sent=1784048118
> synology_network,nas_name=HomeNas01,interface_name=eth1 bytes_recv=3145349500,bytes_sent=4024720623
> synology_network,nas_name=HomeNas01,interface_name=bond0 bytes_recv=5489850543,bytes_sent=5808768741
> 
> Capture #1 complete
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0100 2258 100 192 100 2066 11572 121k --:--:-- --:--:-- --:--:-- 126k
> HTTP/1.1 100 Continue

Hi, 

I had the same issue.
If you have no UPS connected to your NAS, disable the UPS check in the script.
`capture_ups="false" #get UPS status such as runtime, status and charge level.`

**Comment by kernelkaribou** [comment]
Thanks @bboerzel. Changed UPS to be default as not everyone may have an UPS connected
