### ISSUE TITLE
Syntax issues 

### ISSUE THREAD

**Issue by Warlord1390** [kernelkaribou/synology-monitoring#6]
/volume1/MEDIA/Scripts/synology_snmp.sh: line 69: syntax error near unexpected token `elif'
/volume1/MEDIA/Scripts/synology_snmp.sh: line 69: `			elif [[ $line == SYNOLOGY-SYSTEM-MIB::upgradeAvailable.0* ]]; then

This repeats on all elif lines

**Comment by macross5** [comment]
try to start the script with "bash". On my synology the default is sh.

**Comment by Warlord1390** [comment]
I did try that however didn't work, it's all good, ended up going with telegraf with snmp walk
