### ISSUE TITLE
{"error":"database is required"}

### ISSUE THREAD

**Issue by cerlick** [kernelkaribou/synology-monitoring#9]
This has been my favorite Synology Grafana dashboard by far. 

I want to report an issue I did find while getting everything setup. (Possible fix at the end)

The script 'synology_snmp.sh' was not populating any data into the InfluxDB even after updating all the required fields.

Running the script manually from an SSH session showed the following error:
{"error":"database is required"}

The database name field was filed out correctly, and I was able to see the database from the database server itself. 

I did notice something in the CURL commands though:
curl -i -XPOST "http://$influxdb_host:$influxdb_port/write?u=$influxdb_user&p=$influxdb_pass&db=$influxdb_name" --data-binary "$post_url"

What fixed the issue was moving the $influxdb_name before the username and password call:
curl -i -XPOST "http://$influxdb_host:$influxdb_port/write?db=$influxdb_name&u=$influxdb_user&p=$influxdb_pass" --data-binary "$post_url"

After this change, the errors went away and the data started to populate the database as expected. 
InfluxDB shell version: 1.7.10

**Comment by kernelkaribou** [comment]
I updated the script to set the db as the first parameter.  Some searching showed there might have been a regression with versions but implemented after testing as I dont believe it should present other issues.

Thanks!
